# Generated by Django 5.2.5 on 2025-08-22 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Friendly name for this target', max_length=100)),
                ('target_type', models.CharField(choices=[('telegram', 'Telegram'), ('email', 'Email')], default='telegram', max_length=10)),
                ('channel_identifier', models.CharField(blank=True, help_text='Channel identifier (username, ID, or invite link)', max_length=500)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('last_validation_status', models.CharField(choices=[('ok', 'OK'), ('failed', 'Failed'), ('unknown', 'Unknown'), ('pending', 'Pending')], default='unknown', max_length=20)),
                ('last_validation_error', models.TextField(blank=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='accounts.telegramaccount')),
            ],
            options={
                'verbose_name': 'Target',
                'verbose_name_plural': 'Targets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SourceTargetMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('delay_seconds', models.PositiveIntegerField(default=0, help_text='Delay in seconds before processing')),
                ('max_retries', models.PositiveIntegerField(default=3, help_text='Maximum number of retry attempts')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_mappings', to='sources.source')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_mappings', to='targets.target')),
            ],
            options={
                'verbose_name': 'Source-Target Mapping',
                'verbose_name_plural': 'Source-Target Mappings',
                'ordering': ['source', 'target'],
                'unique_together': {('source', 'target')},
            },
        ),
    ]
