# Generated by Django 5.2.5 on 2025-08-22 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Friendly label for this account', max_length=100)),
                ('api_id', models.CharField(max_length=50)),
                ('api_hash', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('session_status', models.CharField(choices=[('ok', 'OK'), ('failed', 'Failed'), ('unknown', 'Unknown'), ('pending', 'Pending'), ('logging_in', 'Logging In'), ('need_code', 'Need Code'), ('need_password', 'Need Password')], default='unknown', help_text='Last known session status: ok/failed/unknown', max_length=20)),
                ('last_error', models.TextField(blank=True, help_text='Last error message')),
                ('pending_phone', models.CharField(blank=True, max_length=20)),
                ('phone_code_hash', models.CharField(blank=True, max_length=100)),
                ('last_check_at', models.DateTimeField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country')),
            ],
            options={
                'verbose_name': 'Telegram Account',
                'verbose_name_plural': 'Telegram Accounts',
                'ordering': ['name'],
            },
        ),
    ]
