# Generated by Django 5.2.5 on 2025-08-22 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_identifier', models.CharField(help_text='Channel identifier (username, ID, or invite link)', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('show_source', models.BooleanField(default=True, help_text='Show source information in forwarded messages')),
                ('mode', models.CharField(choices=[('copy', 'Copy'), ('forward', 'Forward')], default='copy', help_text='Copy or forward mode', max_length=10)),
                ('channel_id', models.BigIntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('invite_link', models.URLField(blank=True)),
                ('is_private', models.BooleanField(default=False)),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('last_validation_status', models.CharField(choices=[('ok', 'OK'), ('failed', 'Failed'), ('unknown', 'Unknown'), ('pending', 'Pending')], default='unknown', max_length=20)),
                ('last_validation_error', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='accounts.telegramaccount')),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Sources',
                'ordering': ['-created_at'],
                'unique_together': {('account', 'input_identifier')},
            },
        ),
    ]
